apiVersion: v1
kind: PersistentVolume
metadata:
  name: my_pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi: 
    driver: efs.csi.aws.com
    volumeHandle: fs-12345678
