apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my_pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
